version: '3'

networks:
  gestore-documentazione-tecnica:

services:
  nginx:
    image: nginx:stable
    container_name: gestore_documentazione_tecnica_standalone_nginx
    volumes:
      - ./src:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - gestore-documentazione-tecnica

  mysql:
    image: mysql:5.7
    container_name: gestore_documentazione_tecnica_standalone_mysql
    environment:
      - MYSQL_USER=gestore_documentazione_tecnica
      - MYSQL_ROOT_PASSWORD=!changeme!
    command: --init-file /setup/create_db.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/setup
    ports:
      - "13306:3306"
    networks:
      - gestore-documentazione-tecnica

  php:
    container_name: gestore_documentazione_tecnica_standalone_php
    hostname: gestore_documentazione_tecnica
    build: docker/php
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - gestore-documentazione-tecnica

volumes:
  mysql_data:
